source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

api_urlpatterns = [
    path("v1/", include("api_v1.urls"))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls")),
    path("accounts/", include('accounts.urls')),
    path("api/", include(api_urlpatterns))
]

source/webapp/urls.py
from django.contrib import admin
from django.urls import path

from webapp.views.product import ProductListView, ProductDetailView, ProductCreate, ProductUpdate, ProductDelete
from webapp.views.basket import add_product, CartView, remove_product
from webapp.views.order import OrderCreateView, UserOrdersView

app_name = "webapp"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", ProductListView.as_view(), name="index"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="views"),
    path("product/create/", ProductCreate.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdate.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDelete.as_view(), name="product_delete"),
    path("<int:pk>/add/", add_product, name="add_product_cart"),
    path("cart/", CartView.as_view(), name="carts"),
    path("<int:pk>/remove/", remove_product, name="remove_product_cart"),
    path("order/create/", OrderCreateView.as_view(), name="order_create"),
    path("user/orders/", UserOrdersView.as_view(), name='user_orders')

]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

class Category(models.Model):
    names = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return f"{self.names}"

    class Meta:
        db_table = "categories"
        verbose_name = "Категория"
        verbose_name_plural = "Категории"



class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name="name")
    descriptions = models.TextField(max_length=2000, blank=True, null=True, verbose_name="description")
    category = models.ForeignKey("webapp.Category", on_delete=models.PROTECT, related_name="categorys")
    count = models.PositiveIntegerField(verbose_name="counts", default=1)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price", null=False, blank=False)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = "products"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Order(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя')
    phone = models.CharField(max_length=30, verbose_name='Телефон')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_order", blank=True, null=True)

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderProduct(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE,
                                verbose_name='Товар', related_name='order_products')
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE,
                              verbose_name='Заказ', related_name='order_products')
    qty = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product.name} - {self.order.name}'

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from webapp.models import Product, Order

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []
        widgets = {
            "category": forms.RadioSelect
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["products", "user"]

source/webapp/views/basket.py
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from webapp.models import Product


def add_product(request, pk):
    if request.method == "GET":
        return HttpResponseNotFound('<h1>Page not found 404</h1>')
    else:
        product = Product.objects.get(pk=pk)
        if "Cart" in request.session:
            key = request.session["Cart"]
            if f'{product.pk}' in request.session["Cart"].keys():
                if key[f"{product.pk}"] < product.count:
                    count = key[f"{product.pk}"]
                    count += 1
                    key[product.pk] = count
                    request.session["Cart"] = key
                    messages.add_message(request, messages.SUCCESS, 'Товар успешно добавлен в количсетве 1!')
                else:
                    messages.add_message(request, messages.ERROR, 'Превышен лимит!')
            else:
                key[product.pk] = 1
                request.session["Cart"] = key
                messages.add_message(request, messages.SUCCESS, 'Товар успешно добавлен в количсетве 1!')
        else:
            request.session["Cart"] = {product.pk: 1}
            messages.add_message(request, messages.SUCCESS, 'Товар успешно добавлен в количсетве 1!')
        return redirect("webapp:index")


def remove_product(request, pk):
    if request.method == "GET":
        return HttpResponseNotFound('<h1>Page not found 404</h1>')
    else:
        product = Product.objects.get(pk=pk)
        if "Cart" in request.session:
            key = request.session["Cart"]
            if f'{product.pk}' in request.session["Cart"].keys():
                if key[f"{product.pk}"] <= 1:
                    del key[f"{product.pk}"]
                    request.session["Cart"] = key
                    messages.add_message(request, messages.WARNING, 'Товар успешно Удален!')
                else:
                    count = key[f"{product.pk}"]
                    count -= 1
                    key[product.pk] = count
                    request.session["Cart"] = key
                    messages.add_message(request, messages.SUCCESS, 'Товар успешно удален в количсетве 1!')
                    return redirect("webapp:carts")
            return redirect("webapp:carts")
        return redirect("webapp:carts")


class CartView(View):
    def get(self, request, *args, **kwargs):
        sums = []
        cont = {}
        if "Cart" in request.session:
            for k, v in request.session["Cart"].items():
                product = Product.objects.get(pk=k)
                cont[product] = v
                sums.append(product.price * v)
        context = {}
        context['product'] = cont
        context['sum'] = sum(sums)
        return render(request, "product/cart.html", context)

source/webapp/views/order.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView

from webapp.forms import OrderForm
from webapp.models import Product, Order, OrderProduct, User


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy("webapp:index")
    template_name = "order/create.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        order = self.object
        if self.request.user.pk:
            order.user = self.request.user
            order.save()

        products = []
        order_products = []
        cont = {}
        for k, v in self.request.session["Cart"].items():
            product = Product.objects.get(pk=k)
            cont[product] = v

        for key, value in cont.items():
            product = key
            qty = value
            product.count -= qty
            products.append(product)
            order_product = OrderProduct(product=product, qty=qty, order=order)
            order_products.append(order_product)
        OrderProduct.objects.bulk_create(order_products)
        Product.objects.bulk_update(products, ("count",))
        del self.request.session["Cart"]
        return response


class UserOrdersView(LoginRequiredMixin, ListView):
    template_name = "order/user_order.html"
    model = Order


    def get_context_data(self, **kwargs):
        ord = Order.objects.filter(user=self.request.user.pk)
        kwargs['user_object'] = ord
        cont = {}

        for key in ord:
            print(key)
            cont[key] = OrderProduct.objects.filter(order=key.pk)

        kwargs['user_object'] = cont
        return super().get_context_data(**kwargs)

source/webapp/views/product.py
from django.contrib import sessions
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, TemplateView

from webapp.models import Product, Category

from webapp.forms import ProductForm


class ProductListView(ListView):
    template_name = "product/index.html"
    model = Product
    context_object_name = "product"
    paginate_by = 10
    paginate_orphans = 1


    # def get(self, request, *args, **kwargs):
    #     if request.session["KEY"]:
    #         key = request.session["KEY"]
    #         count = key[f"{Product.objects.filter(pk=1)}"]
    #         print(type(count))
    #         count += 1
    #         key[f"{Product.objects.filter(pk=1)}"] = f"{count}"
    #         request.session["KEY"][f"{Product.objects.filter(pk=3)}"] = 1
    #     else:
    #         request.session["KEY"] = {f"{Product.objects.filter(pk=1)}": 5}
    #     print(f"{request.session['KEY']=}")
    #     return super().get(request, *args, **kwargs)



    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cont = self.object_list.filter(count__gte=1)
        context['product'] = cont
        return context



class ProductDetailView(DetailView):
    template_name = "product/view.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        context['product'] = product
        return context


class ProductCreate(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = "product/create.html"
    form_class = ProductForm
    permission_required = "webapp.add_product"

    def form_valid(self, form):
        form.save()
        return redirect("webapp:index")

    def form_invalid(self, form):
        context = {"form": form}
        render(self.request, self.template_name, context)


class ProductUpdate(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "product/update.html"
    permission_required = "webapp.change_product"

    def get_success_url(self):
        return reverse("webapp:index")


class ProductDelete(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "product/delete.html"
    permission_required = "webapp.delete_product"

    def post(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:index")

# class AddSessionProduct(CreateView):
#     def post(self, request, *args, **kwargs):
#         product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
#
#         # if request.session["KEY"]:
#         #     key = request.session["KEY"]
#         #     if key[f"{product.pk}"]:
#         #         count = key[f"{product.pk}"]
#         #         count += 1
#         #         key[f"{product.pk}"] = f"{count}"
#         #     else:
#         #         request.session["KEY"][f"{product.pk}"] = 1
#         # else:
#         #     request.session["KEY"] = {f"{product.pk}": 1}
#         # print(f"{request.session['KEY']=}")
#         return super().post(request, *args, **kwargs)
#
#     def get_success_url(self):
#         return redirect("webapp:index")
#
#
# class CartView(ListView):
#     template_name = "product/cart.html"
#     context_object_name = "prod"
#     model = Product
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         if self.request.session["KEY"]:
#             context["product"] = self.request.session["KEY"]
#             print(context["product"])
#         return context

source/webapp/templates/product/cart.html
{% extends "base.html" %}
{% block content %}
    {% include "partial/messages.html" %}
    {% for key, value in product.items %}
        <div style="border: 2px solid black; max-width: 300px; margin-bottom: 20px; padding-left: 15px;border-radius: 33px">
            <p>Название: {{ key.name }}</p>
            <p>Количество: {{ value }}</p>
            <p>Цена: {{ key.price }}</p>
        <form action="{% url "webapp:remove_product_cart" key.pk %}"  method="post">
            {% csrf_token %}
            <button type="submit">Удалить один продукт</button>
        </form>
        <br>
        </div>
    {% empty %}
            <tr>
                <td><h3>Корзина пуста</h3></td>
            </tr>
    {% endfor %}
    {% if sum %}
        <h3><b>Общая цена: {{ sum }}</b></h3>
        <br>
    {% endif %}
    {% if product %}
        <form action="{% url "webapp:order_create" %}"  method="post">
            {% csrf_token %}
            <button type="submit">Сделать заказ</button>
        </form>
    {% endif %}

{% endblock %}

source/webapp/templates/product/create.html
{% extends "base.html" %}

{% block nav %}{% endblock %}
{% block content %}
    <h1>Создать Продукт</h1>

    <form method="post">
        {% include "partial/form.html" with button_text="Создать" %}
    </form>

{% endblock %}>

source/webapp/templates/product/delete.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
    {% csrf_token %}
        <h2>Вы действительно хотите удалить продукт {{ poll.question }}</h2>
        <input type="submit" value="Да">
    </form>
    <a href="{% url "webapp:index" %}">Нет</a>
{% endblock %}

source/webapp/templates/product/index.html
{% extends 'base.html' %}


{% block content %}
     {% include "partial/messages.html" %}
    <h1>Список Продуктов</h1>
{% for pd in product%}
            <div style="border: 2px solid black; max-width: 300px; margin-bottom: 20px; padding-left: 15px;border-radius: 33px">
            <h3 style=" text-overflow: ellipsis; max-width: 300px;white-space: nowrap; overflow:hidden;">{{ pd.name}}</h3>
                <p>{{ pd.descriptions }}</p>
                <p>{{ pd.price }}</p>
            <p><a href="{% url "webapp:views" pd.pk %}">Подробно....</a></p>
            {% if perms.webapp.change_product %}
                <p><a href="{% url "webapp:product_update" pd.pk %}">Редактировать.</a></p>
            {% endif %}
            {% if perms.webapp.delete_product %}
                <p><a href="{% url "webapp:product_delete" pd.pk %}">Удалить.</a></p>
            {% endif %}
                <form action="{% url "webapp:add_product_cart" pd.pk %}"  method="post">
                    {% csrf_token %}
                    <button type="submit">Добавить в корзину</button>
                </form>
                <br>
            </div>

        {% endfor %}


    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/product/update.html
{% extends "base.html" %}

{% block nav %}{% endblock %}
{% block content %}
    <h1>Редактировать продукт</h1>

    <form method="post">
        {% include "partial/form.html" with button_text="Редактировать" %}
    </form>

{% endblock %}>

source/webapp/templates/product/view.html
{% extends "base.html" %}


{% block content %}
        <div style="border: 2px solid black; max-width: 300px; margin-bottom: 20px; padding-left: 15px;border-radius: 33px">
            <h3 style=" text-overflow: ellipsis; max-width: 300px;white-space: nowrap; overflow:hidden;">{{ product.name }}</h3>
            <p>Описание: {{ product.descriptions }}</p>
            <p>Цена: {{ product.price }}</p>
            <p>Категория: {{ product.category }}</p>
            <p>Количество: {{ product.count }}</p>

            <br/>

            </div>
    <p><a href="{% url "webapp:index" %}">На страницу Товаров.</a></p>
{% endblock %}